"""Systemd unit generation for session persistence.

Renders ready-to-install systemd unit files so a launched runtime survives a
reboot. Two flavors are supported:

* :func:`render_api_unit` — a service unit for the Mission Control API itself.
* :func:`render_session_unit` — a per-session unit that relaunches a model's
  runtime. For process runtimes (vLLM, llama.cpp, python scripts) it embeds the
  exact launch command and environment from the session's launch plan. For
  shared-daemon runtimes (Ollama, LM Studio) it emits the unit plus a warning
  pointing at the daemon's own service.

Generation is pure string rendering: nothing is written to disk or enabled here.
"""

from __future__ import annotations

import os
import shlex
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from llmctl.config import Settings, load_settings
from llmctl.db import RuntimeName, SessionKind
from llmctl.schemas import Session
from llmctl.services.sessions import AdoptError

#: Runtimes that run as their own managed daemons; a per-session process unit
#: does not apply (their own service should be enabled instead).
SERVER_RUNTIMES = {RuntimeName.OLLAMA, RuntimeName.LMSTUDIO}


@dataclass
class SystemdUnit:
    """A rendered systemd unit plus install guidance."""

    name: str
    content: str
    user: bool = True
    warnings: list[str] = field(default_factory=list)

    def install_commands(self) -> list[str]:
        """Return the shell commands to install and enable this unit."""
        if self.user:
            unit_dir = "~/.config/systemd/user"
            return [
                f"mkdir -p {unit_dir}",
                f"cat > {unit_dir}/{self.name} <<'EOF'\n{self.content}EOF",
                "systemctl --user daemon-reload",
                f"systemctl --user enable --now {self.name}",
            ]
        unit_dir = "/etc/systemd/system"
        return [
            f"sudo tee {unit_dir}/{self.name} > /dev/null <<'EOF'\n{self.content}EOF",
            "sudo systemctl daemon-reload",
            f"sudo systemctl enable --now {self.name}",
        ]


def _wanted_by(user: bool) -> str:
    """Return the appropriate ``WantedBy`` target for the unit scope."""
    return "default.target" if user else "multi-user.target"


def render_api_unit(settings: Settings | None = None, *, user: bool = True) -> SystemdUnit:
    """Render a systemd unit that runs the Mission Control API server."""
    cfg = settings or load_settings()
    scope = "user" if user else "system"
    cwd = os.getcwd()
    content = (
        f"# llm-mission-control.service ({scope} scope)\n"
        f"# Generated by `llmctl generate-systemd`.\n"
        "[Unit]\n"
        "Description=LLM Mission Control API\n"
        "After=network-online.target\n"
        "Wants=network-online.target\n"
        "\n"
        "[Service]\n"
        "Type=simple\n"
        f"WorkingDirectory={cwd}\n"
        f"ExecStart=llmctl serve --host {cfg.api.host} --port {cfg.api.port}\n"
        "Restart=on-failure\n"
        "RestartSec=5\n"
        "\n"
        "[Install]\n"
        f"WantedBy={_wanted_by(user)}\n"
    )
    return SystemdUnit(name="llm-mission-control.service", content=content, user=user)


def render_session_unit(
    session: Session,
    *,
    user: bool = True,
    working_dir: str | None = None,
) -> SystemdUnit:
    """Render a systemd unit that relaunches ``session``'s runtime on boot.

    Refuses for ``ADOPTED`` sessions: they have no llmctl-issued launch
    command, only a pointer to an externally-managed systemd unit (e.g.
    ``vllm-tp.service``), so generating a unit for them would emit a
    nonsense ``llmctl start None`` placeholder. The caller should
    install the upstream unit directly.
    """
    if session.kind == SessionKind.ADOPTED:
        target = session.systemd_unit or session.endpoint_url or "the upstream unit"
        raise AdoptError(
            f"Session {session.id} is adopted ({target}); llmctl does not own its "
            "launch command. Install the existing systemd unit directly "
            f"(e.g. `sudo systemctl enable {session.systemd_unit or '<unit>'}`)."
        )
    warnings: list[str] = []
    plan = session.launch_plan
    runtime = session.runtime
    short_id = (session.id or "session")[:8]
    label = session.launch_plan.model_name if plan and plan.model_name else session.model_id

    env_lines: list[str] = []
    if plan and plan.env:
        for key, value in plan.env.items():
            env_lines.append(f"Environment={key}={value}")

    if runtime in SERVER_RUNTIMES:
        warnings.append(
            f"{runtime.value} runs as a shared daemon; enable its own service "
            f"(e.g. `systemctl enable {runtime.value}`) for true persistence. "
            "This unit re-applies the session plan via llmctl."
        )
        exec_start = f"llmctl start {session.model_id} --no-dry-run --force"
    elif plan and plan.command:
        exec_start = " ".join(shlex.quote(part) for part in plan.command)
    else:
        warnings.append(
            "Session has no stored launch command; falling back to `llmctl start`."
        )
        exec_start = f"llmctl start {session.model_id} --no-dry-run --force"

    cwd = working_dir or os.getcwd()
    name = f"llmctl-session-{short_id}.service"
    env_block = ("".join(f"{line}\n" for line in env_lines)) if env_lines else ""
    content = (
        f"# {name}\n"
        f"# Generated by `llmctl generate-systemd-session {session.id}`.\n"
        "[Unit]\n"
        f"Description=LLM Mission Control session {short_id} "
        f"({runtime.value} {label or ''})\n"
        "After=network-online.target\n"
        "Wants=network-online.target\n"
        "\n"
        "[Service]\n"
        "Type=simple\n"
        f"WorkingDirectory={cwd}\n"
        f"{env_block}"
        f"ExecStart={exec_start}\n"
        "Restart=on-failure\n"
        "RestartSec=5\n"
        "\n"
        "[Install]\n"
        f"WantedBy={_wanted_by(user)}\n"
    )
    return SystemdUnit(name=name, content=content, user=user, warnings=warnings)


@dataclass
class InstallReport:
    """Result of installing (or planning to install) a systemd unit."""

    unit_path: str
    actions: list[str]
    written: bool
    enabled: bool
    dry_run: bool
    messages: list[str] = field(default_factory=list)


def unit_install_path(unit: SystemdUnit) -> Path:
    """Return the on-disk location a unit would be installed to."""
    if unit.user:
        return Path("~/.config/systemd/user").expanduser() / unit.name
    return Path("/etc/systemd/system") / unit.name


def _systemctl_prefix(user: bool) -> list[str]:
    """Return the ``systemctl`` invocation prefix for the unit scope."""
    return ["systemctl", "--user"] if user else ["sudo", "systemctl"]


def install_unit(
    unit: SystemdUnit, *, dry_run: bool = False, enable: bool = True
) -> InstallReport:
    """Write a unit to disk and reload/enable it via systemctl.

    With ``dry_run`` nothing is written or executed; the report lists the actions
    that *would* run. systemd absence (e.g. inside a container) is handled
    gracefully: the unit file is still written and a clear message is recorded.
    """
    path = unit_install_path(unit)
    systemctl = _systemctl_prefix(unit.user)
    actions = [f"write unit -> {path}", " ".join([*systemctl, "daemon-reload"])]
    if enable:
        actions.append(" ".join([*systemctl, "enable", "--now", unit.name]))

    if dry_run:
        return InstallReport(
            unit_path=str(path),
            actions=actions,
            written=False,
            enabled=False,
            dry_run=True,
            messages=["Dry run: no changes were made."],
        )

    messages: list[str] = []
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(unit.content, encoding="utf-8")
    enabled = False
    try:
        subprocess.run(
            [*systemctl, "daemon-reload"], check=True, capture_output=True, text=True
        )
        if enable:
            subprocess.run(
                [*systemctl, "enable", "--now", unit.name],
                check=True,
                capture_output=True,
                text=True,
            )
            enabled = True
        messages.append(f"Installed {unit.name} ({'enabled' if enabled else 'written'}).")
    except FileNotFoundError:
        messages.append(
            "systemctl not found; wrote the unit file but could not reload/enable it."
        )
    except subprocess.CalledProcessError as exc:
        detail = (exc.stderr or "").strip() or str(exc)
        messages.append(f"systemctl failed: {detail}")
    return InstallReport(
        unit_path=str(path),
        actions=actions,
        written=True,
        enabled=enabled,
        dry_run=False,
        messages=messages,
    )
